from fastapi import APIRouter

from app.api.endpoints import auth, clients, kits, documents, conversations, services, jobs, tools, agreements, hsn_lookup, invoices, vouchers, tally, reconciliation, drive, compliance_calendar, bank_statements, financial_instruments, financial_statements, financial_statements_tally, rule42, pms_accounting, depreciation, caro, form3cd

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(clients.router, prefix="/clients", tags=["clients"])
api_router.include_router(kits.router, prefix="/kits", tags=["kits"])
api_router.include_router(services.router, prefix="/services", tags=["services"])
api_router.include_router(documents.router, prefix="/documents", tags=["documents"])
api_router.include_router(conversations.router, prefix="/conversations", tags=["conversations"])
api_router.include_router(jobs.router, prefix="/jobs", tags=["jobs"])
api_router.include_router(tools.router, prefix="/tools", tags=["tools"])
api_router.include_router(agreements.router, prefix="/agreements", tags=["agreements"])
api_router.include_router(hsn_lookup.router, prefix="/hsn", tags=["hsn"])
api_router.include_router(invoices.router, prefix="/invoices", tags=["invoices"])
api_router.include_router(vouchers.router, prefix="/vouchers", tags=["vouchers"])
api_router.include_router(tally.router, prefix="/tally", tags=["tally"])
api_router.include_router(reconciliation.router, prefix="/reconciliation", tags=["reconciliation"])
api_router.include_router(drive.router, prefix="/drive", tags=["drive"])
api_router.include_router(compliance_calendar.router, prefix="/compliance-calendar", tags=["compliance-calendar"])
api_router.include_router(bank_statements.router, prefix="/bank-statements", tags=["bank-statements"])
api_router.include_router(financial_instruments.router, prefix="/financial-instruments", tags=["financial-instruments"])
api_router.include_router(financial_statements.router, prefix="/financial-statements", tags=["financial-statements"])
api_router.include_router(rule42.router, prefix="/rule42", tags=["rule42"])
api_router.include_router(pms_accounting.router, prefix="/pms", tags=["pms-accounting"])
api_router.include_router(depreciation.router, prefix="/depreciation", tags=["depreciation"])
api_router.include_router(caro.router, prefix="/caro", tags=["caro"])
api_router.include_router(form3cd.router, prefix="/form3cd", tags=["form3cd"])
api_router.include_router(financial_statements_tally.router, prefix="/fs-tally", tags=["fs-tally"])

